### ISSUE TITLE
problem with the directory structure

### ISSUE THREAD

**Issue by martindemello** [jonasmalacofilho/csv-rdp#1]
I had to symlink `lib/format/` to `format/` in order to get `import format.csv.Reader` working.  more details at this stackoverflow post: http://stackoverflow.com/questions/32293107/haxe-cannot-find-a-library-installed-by-haxelib

**Comment by jonasmalacofilho** [comment]
You definitively aren't expected to need a symlink!

The library uses the [`classPath`](http://haxe.org/manual/haxelib-json.html#classPath) directive in [`haxelib.json`](https://github.com/jonasmalacofilho/csv.hx/blob/v0.4.0/haxelib.json#L8) to instruct that the sources are on `/lib`, instead of `/`.

Can you tell me your platform/os and your haxe and haxelib versions?  I'll investigate what might be breaking `classPath`.

**Comment by jonasmalacofilho** [comment]
After making note of the current haxelib version, can you try `haxelib selfupdate`?

**Comment by martindemello** [comment]
selfupdate seems broken on ubuntu too :( i'll take it up with the haxe mailing list.

**Comment by jonasmalacofilho** [comment]
From your message on the mailing list, the ubuntu package is quite old; v3.0.0 was released on May 2013.

In fact, the package you're using most certainly doesn't include the HaxeFoundation/haxelib@ad284d9fe82060a7375fef39eb09956bc6b2ad1e commit that introduced the `classPath` directive.

If you can, I recommend manually installing Haxe 3.2.0 from the [download](http://haxe.org/download/) page.  Even better, try a [nightly](http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/index.html) package or maybe build haxe [yourself](http://haxe.org/documentation/introduction/building-haxe.html).

**Comment by jonasmalacofilho** [comment]
You can also try searching for a suitable PPA.  I found a [reference](https://twitter.com/andy_li/status/607275308358737920) to one by Andy Li.

It really is sad that the default Haxe package on Ubuntu is so out of date.  Fortunately, there have been some recent discussion about improving the availability of both release and nightly packages for all major Linux distributions.

**Comment by martindemello** [comment]
thanks, didn't realise it was that badly out of date! the download version has a missing libneko.so; i'll give building from source a try.

**Comment by martindemello** [comment]
installing from source was quick and easy, and everything works perfectly now. thanks for the help :)

**Comment by jonasmalacofilho** [comment]
Happy to hear that!  : )
